image: golang:1.10

pipelines:
  default:
    - step:
        script:
          - ./bitbucket-pipelines-default.sh

  custom:
    release:
      - step:
          script:
              - ./bitbucket-pipelines-release.sh