image: golang:1.10

pipelines:
  default:
    - step:
        script:
          - bitbucket-pipelines.sh

  custom:
    release:
      - step:
          script:
              - curl -sL https://git.io/goreleaser | bash